### ISSUE TITLE
dbvtk not working when there exist tables as big as 1 GB

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#107]
Description: I suspect that the issue is related to the size of tables because all the smaller databases I tried have been working so far.
I can go to the localhost:8080 with my browser and even see the structure of the database. But under the data if I click on the tables then first 5 work nicely but the sixth table (evpkr->isoper sized about 1 GB) gives me a message "No items to display" although on the diagram view dbvtk draw the biggest bubble and showed the table contains over 5 million records.
When I click on the tables (7, 8, 9, ...) after isoper then these will keep loading and get me an error "Generic exception Could not query index"

![genericexception](https://cloud.githubusercontent.com/assets/3479156/24492890/7f9ab804-1535-11e7-88d4-2061c15383b4.png)

The upload process also gave me an error.
```
2017-03-30 09:58:56,314 [http-nio-8080-exec-3] ERROR c.d.v.c.c.utils.AsyncCallbackUtils - [0:0:0:0:0:0:0:1] AsyncCallback error - GenericException: Could not query index
com.google.gwt.core.shared.SerializableThrowable: Could not query index
	at Unknown.yI(Throwable.java:116) ~[na:na]
	at Unknown.vI(Throwable.java:55) ~[na:na]
	at Unknown.BI(Exception.java:25) ~[na:na]
	at Unknown.Ndc(RODAException.java:18) ~[na:na]
	at Unknown.hec(GenericException.java:19) ~[na:na]
	at Unknown.jec(GenericException_FieldSerializer.java:16) ~[na:na]
	at Unknown.KIb(SerializerBase.java:55) ~[na:na]
	at Unknown.Kb(SerializerBase.java:112) ~[na:na]
	at Unknown.nHb(AbstractSerializationStreamReader.java:119) ~[na:na]
	at Unknown.OHb(RequestCallbackAdapter.java:216) ~[na:na]
	at Unknown.c_(Request.java:250) ~[na:na]
	at Unknown.p_(RequestBuilder.java:412) ~[na:na]
	at Unknown.anonymous(XMLHttpRequest.java:329) ~[na:na]
	at Unknown.sR(Impl.java:247) ~[na:na]
	at Unknown.vR(Impl.java:299) ~[na:na]
	at Unknown.anonymous(Impl.java:72) ~[na:na]
2017-03-30 10:08:24,349 [http-nio-8080-exec-2] DEBUG org.apache.http.headers - >> GET /solr/dbv-database/
```

Let me know if you want some more input.

**Comment by chalkos** [comment]
Hi Lauri, when you converted the DB with DBPTK did it output any errors? The log file can also be useful if you are allowed to upload that (or sent it via email).

Are you using windows or linux?
For big databases, the memory given to Solr and DBPTK may need to be increased for everything to work properly.

**Comment by Laurira** [comment]
I opened the log and there is only two SQLExceptions related to some symbols? But for the big table isoper, everything seems to be working. I will send the log file to your email, Bruno.

**Comment by Laurira** [comment]
This is the log file from dbptk.

 

Thanks,

Lauri

**Comment by chalkos** [comment]
Status report: This issue is being discussed by email.

Apparently there are some errors when converting the database from the DBMS to Solr. The errors are related to MySQL providing a non-date value when the column has DATE type, and the invalid cells are saved as NULL.

Since SolrExportModule is able to handle NULLs just fine, the described error is probably not related to the DBVTK error.

My guess is that Solr ran out of memory while processing (maybe while committing?) the big table, and then it shutdown or refused to process more data sent by the DBPTK.

**Comment by luis100** [comment]
This issue is superseeded by #135
