### ISSUE TITLE
connection problem to oracle database - centos 7

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#182]
With command line the connection works rather quickly. I can generate the table list for about 15 minutes.

I started stopwatch when I clicked "Next" after inserting connection parameters to the dbvtk.

It has been 40 hours
![image](https://user-images.githubusercontent.com/3479156/69852238-7112cb80-128c-11ea-8444-c02af01c2655.png)

Parameters:
![image](https://user-images.githubusercontent.com/3479156/69852553-3c534400-128d-11ea-889c-145f38b6ac95.png)
I do not "Count Rows"
![image](https://user-images.githubusercontent.com/3479156/69852668-8c320b00-128d-11ea-8f55-9a81040cbcc0.png)

I have deleted .dbvtk and .dbptk folders...

Today is Friday, last log has been modified 2 days ago...
![image](https://user-images.githubusercontent.com/3479156/69852338-acad9580-128c-11ea-8816-8e7bb2249429.png)

I also tried to connect without SSH tunnel and it still keeps thinking... (waited for an hour and still nothing)

With DBeaver the same parametrs get result in 8 seconds
![image](https://user-images.githubusercontent.com/3479156/69852969-517ca280-128e-11ea-94bb-ac70d679a391.png)

**Comment by Laurira** [comment]
Only log I have is this:

2019-11-29 09:45:48,052 [main] INFO  c.d.c.server.ViewerConfiguration - Copying files from classpath prefix=config/, destination=/home/laurir/.dbvtk/example-config, removePrefix=true, excludePaths=[config/i18n/client, config/i18n/I18N.gwt.xml]
2019-11-29 09:45:48,201 [main] INFO  c.d.c.server.ViewerConfiguration - DBVTK loading completed with success!

**Comment by Laurira** [comment]
Seems like there is no something in the JVM log:
2019-11-29 10:01:06.799  INFO 8828 --- [o-auto-1-exec-4] c.d.m.o.in.Oracle12cJDBCImportModule     : Obtaining routine Z_ADS_GML_TO_GEO
2019-11-29 10:01:13.561 ERROR 8828 --- [o-auto-1-exec-3] Uncaught                                 : [127.0.0.1] Uncaught Exception: in == null

com.google.gwt.core.shared.SerializableThrowable: in == null
	at Unknown.dDb(Throwable.java:66) ~[na:na]
	at Unknown.nDb(Exception.java:29) ~[na:na]
	at Unknown.pDb(RuntimeException.java:29) ~[na:na]
	at Unknown.xed(JsException.java:30) ~[na:na]
	at Unknown.FHb(NonBufferedJsonReader.java:290) ~[na:na]
	at Unknown.NBb(JsonDeserializationContext.java:335) ~[na:na]
	at Unknown.A$(AbstractObjectMapper.java:57) ~[na:na]
	at Unknown.nzb(AbstractObjectMapper.java:51) ~[na:na]
	at Unknown.qzb(TableAndColumns.java:173) ~[na:na]
	at Unknown.wUc(RequestCallbackAdapter.java:232) ~[na:na]
	at Unknown.tXb(Request.java:250) ~[na:na]
	at Unknown.IXb(RequestBuilder.java:412) ~[na:na]
	at Unknown.anonymous(XMLHttpRequest.java:329) ~[na:na]
	at Unknown.KMb(Impl.java:309) ~[na:na]
	at Unknown.NMb(Impl.java:361) ~[na:na]
	at Unknown.anonymous(Impl.java:78) ~[na:na]

So it seems it is trying to list the routines and one of these gets an error?




File itself:
[JVM-log.log](https://github.com/keeps/db-visualization-toolkit/files/3904315/JVM-log.log)

**Comment by Laurira** [comment]
Great news, the fix you provided me connected the 800GB database under 1 minute...

**Comment by Laurira** [comment]
This is the first glinch
![image](https://user-images.githubusercontent.com/3479156/70436528-31b95b80-1a92-11ea-9324-f864ad9ac000.png)

**Comment by Laurira** [comment]
So you can close this issue, good job.

**Comment by hmiguim** [comment]
Close at: 7d2e578
